name: sample_app
description: BiosenseSignal Sample App.
publish_to: 'none'

version: 5.6.1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  biosensesignal_flutter_sdk:
    path: ./BiosenseSignal_Flutter_SDK_5.6.3

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.13
  permission_handler: ^11.3.1
  focus_detector: ^2.0.1
  provider: ^6.0.1
  fluttertoast: ^8.1.1
  wakelock_plus: ^1.2.8

dependencies_overrides:
  win32: ^5.8.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/